config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users, only: [:show, :update]

  get 'home/index'
  root 'home#index'

  get 'home/info'
  get 'home/export'
  get 'home/kits'

  get 'kits/XR250_XR400'
  get 'kits/XR600'
  get 'kits/XR650L'
  get 'kits/replacement'
  get 'kits/rear_fenders_1'
  get 'kits/rear_fenders_2'
  get 'kits/graphics'

  get 'other/xr400mx'

  resources :products
  get 'tags/:tag', to: 'products#index', as: :tag
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :orders, only: [:update, :edit, :show, :create, :index]
  get 'orders/update'
  put "orders/:id/mark_as_placed" => "orders#mark_as_placed", as: "mark_as_placed"
  put "orders/:id/mark_as_shipped" => "orders#mark_as_shipped", as: "mark_as_shipped"
  put "orders/:id/mark_as_cancelled" => "orders#mark_as_cancelled", as: "mark_as_cancelled"

  resources :contacts
  put "contacts/:id/archive" => "contacts#archive", as: "archive_contact"
  put "contacts/:id/unarchive" => "contacts#unarchive", as: "unarchive_contact"

  resources :photos
  put "photos/:id/approve" => "photos#approve", as: "approve_photo"
  put "photos/:id/unapprove" => "photos#unapprove", as: "unapprove_photo"

  resources :charges, only: [:new, :create]
  get 'charges/address'
  get 'charges/shipping'
  post 'charges/update_order'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	@unapproved_photos = Photo.where(approved: false)
    @orders = Order.where(user_id: current_user.id).order('date_placed DESC')
    @current_orders = Order.where(order_status_id: 2)
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(account_update_params)
    if @user.update(account_update_params)
      redirect_to charges_shipping_path
    else
      render :back
      flash[:notice] = "Something is amuck."
    end
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password, :phone, :admin, :stripe_customer_id, :street_address_1, :street_address_2, :city, :state, :zip, :provence, :country, :has_shipping)
  end
end

app/views/users/_current_orders.html.erb
<h2 class="small-h2">Current Orders</h2>
<p>Here are the details for the currently outstanding orders.</p>

<table>
  <tr>
    <th>Order Number</th>
    <th>Date Placed</th>
    <th>Order Status</th>
    <th>Amount</th>
    <th>Change Order Status</th>
  </tr>
  <% @current_orders.each do |order| %>
    <% if order.date_placed != nil %>
        <tr>
          <td><%= link_to order.id, order_path(order)%></td>
          <td><%= order.date_placed.strftime('%a, %b %d, %G, %T %Z') %></td>
          <td><%= order.order_status.name %></td>
          <td><%= number_to_currency(order.total) %></td>
          <td>
            <%= link_to mark_as_placed_path(order), method: :put, data: {confirm: "Are you sure you want to mark this order as placed?"} do %>
              <i class="icon ion-clock" style="font-size: 20px"></i>
            <% end %>
            <%= link_to mark_as_shipped_path(order), method: :put, data: {confirm: "Are you sure you want to mark this order as shipped?"} do %>
              <i class="icon ion-map" style="font-size: 20px"></i>
            <% end %>
            <%= link_to mark_as_cancelled_path(order), method: :put, data: {confirm: "Are you sure you want to cancel this order?"} do %>
              <i class="icon ion-close-round" style="font-size: 20px"></i>
            <% end %>
          </td>
          </tr>
    <% end %>
  <% end %>
</table>

<h4 class="text-center"><%= link_to "Click Here to See All Orders", orders_path %></h4>


<script type="text/javascript">
  $('.open-popup-link').magnificPopup({
    type:'inline',
    midClick: true
  });
</script>

app/views/users/_gallery_approvals.html.erb
<h2 class="small-h2">New Gallery Submissions</h2>
<p>Click on each picture to approve, edit, or reject it.</p>

<% @unapproved_photos.each do |photo| %>
   <div class="col-xs-4 col-sm-3 col-md-2 col-lg-1 big-div">
        <a href="#<%= photo.id %>" class="open-popup-link">
             <div class="snapshot">
               <% if photo.image.attached? %>
                  <%= image_tag url_for(photo.image), alt: photo.user.last_name %>
                <% end %>
             </div> <!-- snapshot -->
        </a>
   </div> <!-- column -->

   <div id="<%= photo.id %>" class="image-popup mfp-hide text-center">
      <% if photo.image.attached? %>
        <%= image_tag url_for(photo.image), alt: photo.user.last_name, class: "popup-picture", style: "margin-bottom: 30px" %>
      <% end %>
        <p><%= photo.comments %></p>
        <h3><strong>Submitted by: </strong><%= photo.user.first_name %></h3>
        <% if current_user && current_user.admin %>
            <div class="row">
            	<div class="col-xs-4 col-sm-2 col-sm-push-3">
		            <%= link_to edit_photo_path(photo) do %>
		                  <i class="icon large ion-edit"></i>
		                  <br>Edit This Photo
		            <% end %>
	            </div> <!-- column -->
	            <div class="col-xs-4 col-sm-2 col-sm-push-3">
		            <%= link_to approve_photo_path(photo), method: :put, style: "color: green" do %>
		            	<i class="icon large ion-checkmark-round"></i>
		            	<br>Approve This Photo
		            <% end %>
	            </div> <!-- column -->
	            <div class="col-xs-4 col-sm-2 col-sm-push-3">
		            <%= link_to photo_path(photo), method: :delete, data: {confirm: "Are you sure you want to delete this photo?"}, style: "color: red" do %>
		            	<i class="icon large ion-trash-a"></i>
		            	<br>Delete This Photo
		            <% end %>
	            </div> <!-- column -->
            </div> <!-- approval row -->
        <% end %>
   </div>  <!-- mfp contents -->
<% end %>


<script type="text/javascript">
  $('.open-popup-link').magnificPopup({
    type:'inline',
    midClick: true
  });
</script>

app/views/users/_orders.html.erb
<h2 class="small-h2">My Orders</h2>
<p>Here are the details for all of your previous orders.</p>

<table>
  <tr>
    <th>Order Number</th>
    <th>Date Placed</th>
    <th>Order Status</th>
    <th>Amount</th>
  </tr>
  <% @orders.each do |order| %>
    <% if order.date_placed != nil %>
        <tr>
          <td><%= link_to order.id, order_path(order)%></td>
          <td><%= order.date_placed.strftime('%a, %b %d, %G, %T %Z') %></td>
          <td><%= order.order_status.name %></td>
          <td><%= number_to_currency(order.total) %></td>
        </tr>
    <% end %>
  <% end %>
</table>


<script type="text/javascript">
  $('.open-popup-link').magnificPopup({
    type:'inline',
    midClick: true
  });
</script>

app/views/users/show.html.erb
<div class="hero-image-row">
    <div class="hero-image-outer text-center">
        <div class="hero-image-inner text-center">
            <%= image_tag "polaris_8.jpg", class: "hero-image", alt: "Asphalt road with clouds." %>
        </div> <!-- hero-image-inner -->
    </div> <!-- hero-image-inner -->
</div> <!-- row -->

<div class="overlap-hero-image">
    <div class="index-text row">
        <% if current_user.admin %>
            <h2>Admin Dashboard</h2>
        <% else %>
            <h2>My Account</h2>
        <% end %>
    </div> <!-- index text row -->
</div> <!-- overlap hero image -->


<div class="text-center header-row row background-white" style="padding-top: 30px">
    <p>
        <small><%= @user.first_name %> <%= @user.last_name %> | <%= @user.email %><% if @user.phone %> | </strong><%= @user.phone %><% end %></small><br>
        <%= link_to "Edit My Information", edit_user_registration_path %> | <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %><br>
    </p>
</div> <!-- centered header -->

<div class="row bp50 background-white">
    <div class="container">
        <% if current_user.admin %>
            <div class="row"><%= render 'gallery_approvals' %></div>
            <div class="row"><%= render 'current_orders' %></div>
        <% else %>
          <div class="row"><%= render 'orders' %></div>

        <% end %>
    </div> <!-- page container -->
</div> <!-- white row -->

app/views/users/update.js.erb
$(".shipping-info").html("<%= escape_javascript(render 'charges/shipping') %>")