config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users, only: [:show, :update]

  get 'home/index'
  root 'home#index'

  get 'home/info'
  get 'home/export'
  get 'home/kits'

  get 'kits/XR250_XR400'
  get 'kits/XR600'
  get 'kits/XR650L'
  get 'kits/replacement'
  get 'kits/rear_fenders_1'
  get 'kits/rear_fenders_2'
  get 'kits/graphics'

  get 'other/xr400mx'

  resources :products
  get 'tags/:tag', to: 'products#index', as: :tag
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :orders, only: [:update, :edit, :show, :create, :index]
  get 'orders/update'
  put "orders/:id/mark_as_placed" => "orders#mark_as_placed", as: "mark_as_placed"
  put "orders/:id/mark_as_shipped" => "orders#mark_as_shipped", as: "mark_as_shipped"
  put "orders/:id/mark_as_cancelled" => "orders#mark_as_cancelled", as: "mark_as_cancelled"

  resources :contacts
  put "contacts/:id/archive" => "contacts#archive", as: "archive_contact"
  put "contacts/:id/unarchive" => "contacts#unarchive", as: "unarchive_contact"

  resources :photos
  put "photos/:id/approve" => "photos#approve", as: "approve_photo"
  put "photos/:id/unapprove" => "photos#unapprove", as: "unapprove_photo"

  resources :charges, only: [:new, :create]
  get 'charges/address'
  get 'charges/shipping'
  post 'charges/update_order'
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_one_attached :image

	acts_as_taggable
	has_many :order_items

	default_scope { where(active: true) }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  def index
    @order_item = current_order.order_items.new

    if params[:tag]
      @products = Product.tagged_with(params[:tag]).order("created_at ASC")
    else
      @products = Product.order("created_at ASC")
    end
  end

  # GET /products/1
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  def create
    @product = Product.new(product_params)

    if @product.save
      @product.image.purge
      @product.image.attach(params[:image])
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def product_params
      params.require(:product).permit(:name, :tag_line, :description, :application_notes, :size, :aloop_number, :price, :image, :active, :tag_list, :weight, :envelope, :box_length, :box_width, :box_depth)
    end
end

app/views/products/_form.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-push-1">
    <%= simple_form_for(@product) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs row">
        <div class="form-group col-xs-9">
          <%= f.label "Product Name" %>
          <%= f.text_field :name, class: "form-control" %>
        </div> <!-- form group -->

        <div class="form-group col-xs-3">
          <%= f.label :price %>
          <%= f.text_field :price, class: "form-control", data: {autonumeric: true} %>
        </div> <!-- form group -->

        <div class="form-group col-xs-12">
          <%= f.label :tag_list, "Tags (separated by commas)" %><br />
          <%= f.input :tag_list, label: false, :input_html => { :class => "css-class", :value => @product.tag_list.join(", ") } %>

        </div> <!-- form group -->

        <div class="form-group col-xs-6">
          <%= f.label "Product Size" %>
          <%= f.text_field :size, class: "form-control" %>
        </div> <!-- form group -->

        <div class="form-group col-xs-6">
          <%= f.label "Aloop Product Number" %>
          <%= f.text_field :aloop_number, class: "form-control" %>
        </div> <!-- form group -->

        <div class="form-group col-xs-12">
          <%= f.label "Product Tag Line" %>
          <%= f.text_field :tag_line, class: "form-control" %>
        </div> <!-- form group -->

        <div class="form-group col-xs-12">
          <%= f.label "Product Description" %>
          <%= f.text_area :description, class: "form-control" %>
        </div> <!-- form group -->

        <div class="form-group col-xs-12">
          <%= f.label "Application Notes" %>
          <%= f.text_area :application_notes, class: "form-control" %>
        </div> <!-- form group -->

        <div class="form-group col-xs-12">
          <%= f.file_field :image %>
        </div> <!-- form group -->

        <div class="form-group text-center col-xs-12">
           <%= f.input :active, label: "This is an active product." %>
        </div> <!-- form group -->

        <div class="col-xs-12">
          <h2 class="text-center">Shipping Information</h2>
        </div>

        <div class="form-group col-xs-6">
          <%= f.label "Product Length (in Inches)" %>
          <%= f.text_field :box_length, class: "form-control" %>
        </div> <!-- form group -->

        <div class="form-group col-xs-6">
          <%= f.label "Product Width (in Inches)" %>
          <%= f.text_field :box_width, class: "form-control" %>
        </div> <!-- form group -->

        <div class="form-group col-xs-6">
          <%= f.label "Product Depth (in Inches)" %>
          <%= f.text_field :box_depth, class: "form-control" %>
        </div> <!-- form group -->

        <div class="form-group col-xs-6">
          <%= f.label "Product Weight (in Pounds)" %>
          <%= f.text_field :weight, class: "form-control" %>
        </div> <!-- form group -->

        <div class="form-group text-center col-xs-12">
           <%= f.input :envelope, label: "This product ships in an envelope." %>
        </div> <!-- form group -->

      </div>

      <div class="form-actions text-center">
        <%= f.button :submit %>
      </div>
    <% end %>
  </div> <!-- column -->
</div> <!-- form row -->

app/views/products/_product_row.html.erb
<div class="row">
  <div class="col-sm-3 text-center">
    <% if product.image.attached? %>
      <%= image_tag url_for(product.image), alt: product.name, style: "padding: 20px; max-width: 100%; max-height: 250px" %>
    <% end %>
    <p><small><%= product.aloop_number %><% if product.size != "" %>, <%= product.size %><% end %></small></p>
    <h3><strong>$<%= number_with_precision(product.price, precision: 2) %></strong></h3>
  </div> <!-- image -->

  <div class="col-sm-9 text-left">
    <h1 style="font-size: 30px">
      <%= link_to product, class: "color-transparent-black", style: "text-transform: uppercase; font-weight: 900" do %>
        <%= product.name %>
      <% end %>
      <% if current_user && current_user.admin %>
          <%= link_to edit_product_path(product) do %>
            <small><i class="icon ion-edit"></i></small>
          <% end %>
          <%= link_to product_path(product), method: :delete, data: { confirm: 'Are you sure?' } do %>
            <small><i class="icon ion-trash-a"></i></small>
          <% end %>
      <% end %>
    </h1>
    <p><strong><%= product.tag_line %></strong></p>
    <!-- <p><%= product.description %></p> -->
    <p><em><%= product.application_notes %></em></p>
    <% if product.tag_list != [] %>
      <p>Tags: <%= raw product.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></p>
    <% end %>

    <%= form_for order_item, remote: true do |f| %>
      <div class="input-group">
        <%= f.number_field :quantity, value: 1, class: "form-control", min: 1, style: "width: 80px; height: 40px; margin-right: 20px; margin-top: 5px; display: inline-block" %>
        <div style="display: inline-block">
          <%= f.hidden_field :product_id, value: product.id %>
          <%= f.submit "Add to Cart", class: "btn", style: "margin-top: 0px" %><span class="hidden addedToCart" style="color: green; font-weight: bold; margin-left: 20px">Added to Cart</span>
        </div>
      </div>
    <% end %>
  </div> <!-- info -->
</div> <!-- row -->

<div class="row">
  <hr class="col-xs-push-2 col-xs-8" />
</div> <!-- row -->

app/views/products/edit.html.erb
<div class="row">
	<div class="blue-box col-xs-10 col-xs-push-1">
		<div class="header-row text-center row">
			<h2>Edit <%= @product.name %></h2>
		  	<%= image_tag "tire_tracks.jpg", class: "tracks", alt: "Tire track marks", style: "max-height: 80px; width: auto" %>
		</div> <!-- header row -->

		<%= render 'form' %>

		<div class="text-center">
			<%= link_to 'Show', @product %> |
			<%= link_to 'Back', products_path %>
		</div> <!-- centered -->
	</div> <!-- blue box -->
</div> <!-- row -->

<script type="text/javascript">
  $(document).ready(function(){
    $(".footer").removeClass("top-shadow-inset");
  });
</script>

app/views/products/index.html.erb
<div class="hero-image-row">
  <div class="hero-image-outer text-center">
    <div class="hero-image-inner text-center">
      <%= image_tag "polaris_3.jpg", class: "hero-image", alt: "Asphalt road with clouds." %>
    </div> <!-- hero-image-inner -->
  </div> <!-- hero-image-inner -->
</div> <!-- row -->

<div class="overlap-hero-image">
  <div class="index-text row">
    <h2>Aloop Store</h2>
  </div> <!-- index text row -->
</div> <!-- overlap hero image -->

<div class="row text-center background-white bottom-shadow" style="padding-bottom: 25px; margin-bottom: 50px">
  <div class="row">
    <div class="container">
      <h2>Aloop Kits</h2>

      <div class="col-sm-4 inner-15">
        <div class="black-box hover store-featured">
          <div class="image-box">
            <%= image_tag "kit_1_1.jpg", alt: "Aloop 4SMX Seat/Tank Kit for XR250 and XR400" %>
          </div> <!-- image box -->
          <div class="text-box">
            <h3>4SMX Kit for XR250/XR400</h3>
            <p>The most popular XR400 performance modification in the world!</p>
            <%= form_for @order_item, remote: true do |f| %>
    						<%= f.hidden_field :quantity, value: 1 %>
    						<%= f.hidden_field :product_id, value: 1 %>
    						<%= f.submit "Add to Cart", class: "btn cta btn1", style: "margin-top: 0px" %><span class="hidden addedToCart1" style="color: green; font-weight: bold; margin-left: 20px">Added to Cart</span>
    				<% end %>
          </div> <!-- text-box -->
        </div> <!-- black box -->
      </div> <!-- column -->

      <div class="col-sm-4 inner-15">
        <div class="black-box hover store-featured">
          <div class="image-box">
            <%= image_tag "kit_2_1.jpg", alt: "Aloop 4SMX Seat/Tank Kit for XR600" %>
          </div> <!-- image box -->
          <div class="text-box">
            <h3>4SMX Kit for XR600</h3>
            <p>The most popular XR400 performance modification in the world!</p>
            <%= form_for @order_item, remote: true do |f| %>
    						<%= f.hidden_field :quantity, value: 1 %>
    						<%= f.hidden_field :product_id, value: 2 %>
    						<%= f.submit "Add to Cart", class: "btn cta btn2", style: "margin-top: 0px" %><span class="hidden addedToCart2" style="color: green; font-weight: bold; margin-left: 20px">Added to Cart</span>
    				<% end %>
          </div> <!-- text-box -->
        </div> <!-- black box -->
      </div> <!-- column -->

      <div class="col-sm-4 inner-15">
        <div class="black-box hover store-featured">
          <div class="image-box">
            <%= image_tag "kit_3_1.jpg", alt: "Aloop 4SMX Seat/Tank Kit for XR650L" %>
          </div> <!-- image box -->
          <div class="text-box">
            <h3>4SMX Kit for XR650L</h3>
            <p>The most popular XR400 performance modification in the world!</p>
            <%= form_for @order_item, remote: true do |f| %>
    						<%= f.hidden_field :quantity, value: 1 %>
    						<%= f.hidden_field :product_id, value: 3 %>
    						<%= f.submit "Add to Cart", class: "btn cta btn3", style: "margin-top: 0px" %><span class="hidden addedToCart3" style="color: green; font-weight: bold; margin-left: 20px">Added to Cart</span>
    				<% end %>
          </div> <!-- text-box -->
        </div> <!-- black box -->
      </div> <!-- column -->

    </div> <!-- container -->
  </div> <!-- black box row -->
</div>

<div class="header-row row text-center">
  <div class="col-xs-10 col-xs-push-1 blue-box">
    <div class="text-right">
      <% if current_user && current_user.admin %>
        <%= link_to 'New Product', new_product_path, style: "padding: 15px" %>
      <% end %>
    </div> <!-- right nav -->

    <div class="row">
      <h2>Aloop Products</h2>
      <h3>Along with our game-changing 4SMX kits, we now carry other plastic parts to help convert your XR into a genuine 4SMX weapon.</h3>
      <h3><strong>Click on a tag below to sort through our products or browse the entire catalogue below.</strong></h3>

      <div class="row">
        <div id="tag_cloud" class="col-sm-6 col-sm-push-3" style="margin-top: 20px">
          <% tag_cloud Product.tag_counts, %w{s m l} do |tag, css_class| %>
            <%= link_to tag.name, tag_path(tag.name), class: css_class %>
          <% end %>
        </div> <!-- tag cloud -->
      </div> <!-- tag cloud row -->
    </div> <!-- row -->

    <div class="row">
      <hr class="col-xs-push-2 col-xs-8" />
    </div> <!-- row -->

    <div class="row">
      <% @products.each do |product| %>
        <%= render "product_row", product: product, order_item: @order_item %>
      <% end %> <!-- each ends -->
    </div> <!-- row -->

    <div class="row text-center">
      <h4>Can't find what you're looking for?  <%= link_to "Contact us", new_contact_path %> and we'll help you find it!</h4>
    </div>

  </div> <!-- column -->
</div> <!-- header row -->

<script type="text/javascript">
  $(document).ready(function(){
    $(".footer").removeClass("top-shadow-inset");
    $(".btn1").click(function(){
      $(".addedToCart1").removeClass("hidden");
    });
    $(".btn2").click(function(){
      $(".addedToCart2").removeClass("hidden");
    });
    $(".btn3").click(function(){
      $(".addedToCart3").removeClass("hidden");
    });
  });
</script>

app/views/products/new.html.erb
<div class="row">
	<div class="blue-box col-xs-10 col-xs-push-1">
		<div class="header-row text-center row">
			<h2>Add a New Product</h2>
		  	<%= image_tag "tire_tracks.jpg", class: "tracks", alt: "Tire track marks", style: "max-height: 80px; width: auto" %>
		</div> <!-- header row -->

		<%= render 'form' %>

		<div class="text-center row">
			<%= link_to 'Back', products_path %>
		</div> <!-- bottom centered row -->
	</div> <!-- blue box -->
</div> <!-- row -->

<script type="text/javascript">
  $(document).ready(function(){
    $(".footer").removeClass("top-shadow-inset");
  });
</script>

app/views/products/show.html.erb
<p class="text-right" style="padding: 10px 20px 0 0">
  <%= link_to "Back to Store", products_path %>
  <% if current_user && current_user.admin %>
    |  <%= link_to "Edit Product", edit_product_path(@product) %>
  <% end %>
</p>

<div class="row">
  <div class="row">
    <div class="black-box col-xs-10 col-xs-push-1">
      <div class="header-row row text-center">
        <div class="container">
          <h2><%= @product.name %></h2>
          <% if @product.tag_list != [] %>
            <p><strong>Tags: </strong><%= raw @product.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></p>
          <% end %>
          <p>
            Aloop Part #<%= @product.aloop_number %>
            <% if @product.size != "" %>, <%= @product.size %><% end %>
          </p>

          <% if @product.active == false %>
            <h3 class="color-red">No Longer Available</h3>
          <% else %>
            <h3>$<%= number_with_precision(@product.price, precision: 2) %></h3>
          <% end %>


          <div class="product-image">
            <a href="#popup-1" class="open-popup-link">
              <% if @product.image.attached? %>
                <%= image_tag url_for(@product.image), alt: @product.name, style: "padding: 20px" %>
              <% end %>
            </a>
          </div> <!-- product image -->

        </div> <!-- container -->
      </div>


      <div class="row product-row">
        <div class="container">

          <% if @product.description != "" %>
            <p><strong>Product Description: </strong><%= @product.description %></p>
          <% end %> <!-- description -->

          <% if @product.application_notes != "" %>
            <p><strong>Application notes: </strong><%= @product.application_notes %></p>
          <% end %> <!-- application notes -->

          <div class="text-center">
            <h1>
              <% if @product.tag_line != "" %>
                <strong><%= @product.tag_line %></strong>
              <% else %>
                <strong>Get yours today!</strong>
              <% end %>
            </h1>

            <div class="btn cta"><%= link_to "Add to Cart" %></div>

            <div class="row">
              <hr class="col-sm-6 col-sm-push-3">
            </div>

            <p>
              <%= link_to "Return to Store", products_path %> |
              <% if current_user && current_user.admin %>
                <%= link_to 'Edit Product', edit_product_path(@product) %> |
              <% end %>
              <%= link_to 'Back', products_path %>
            </p>

        </div> <!-- container -->
      </div> <!-- row -->

      <% if current_user && current_user.admin %>
        <div class="row shipping info">
          <div class="container">
            <h3> Shipping Information</h3>
            <p><strong>Length: </strong><%= @product.box_length %> Inches<br />
              <strong>Width: </strong><%= @product.box_width %> Inches<br />
              <strong>Depth: </strong><%= @product.box_depth %> Inches<br />
              <strong>Weight: </strong><%= @product.weight %> Lbs.<br />
              <strong>Envelope: </strong><% if @product.envelope %>Yes<% else %>No<% end %>
            </p>
          </div> <!-- container -->
        </div> <!-- shipping info row -->
      <% end %>
    </div> <!-- black border box -->
  </div> <!-- row -->
</div> <!-- row -->



<script type="text/javascript">
  $(document).ready(function(){
    $(".footer").removeClass("top-shadow-inset");
  });
</script>



<script type="text/javascript">
  $('.open-popup-link').magnificPopup({
    type:'inline',
    midClick: true // Allow opening popup on middle mouse click. Always set it to true if you don't provide alternative source in href.
  });
</script>

<div id="popup-1" class="image-popup mfp-hide text-center">
  <% if @product.image.attached? %>
    <%= image_tag url_for(@product.image), alt: @product.name, class: "popup-picture" %>
  <% end %>
</div>