config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users, only: [:show, :update]

  get 'home/index'
  root 'home#index'

  get 'home/info'
  get 'home/export'
  get 'home/kits'

  get 'kits/XR250_XR400'
  get 'kits/XR600'
  get 'kits/XR650L'
  get 'kits/replacement'
  get 'kits/rear_fenders_1'
  get 'kits/rear_fenders_2'
  get 'kits/graphics'

  get 'other/xr400mx'

  resources :products
  get 'tags/:tag', to: 'products#index', as: :tag
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :orders, only: [:update, :edit, :show, :create, :index]
  get 'orders/update'
  put "orders/:id/mark_as_placed" => "orders#mark_as_placed", as: "mark_as_placed"
  put "orders/:id/mark_as_shipped" => "orders#mark_as_shipped", as: "mark_as_shipped"
  put "orders/:id/mark_as_cancelled" => "orders#mark_as_cancelled", as: "mark_as_cancelled"

  resources :contacts
  put "contacts/:id/archive" => "contacts#archive", as: "archive_contact"
  put "contacts/:id/unarchive" => "contacts#unarchive", as: "unarchive_contact"

  resources :photos
  put "photos/:id/approve" => "photos#approve", as: "approve_photo"
  put "photos/:id/unapprove" => "photos#unapprove", as: "unapprove_photo"

  resources :charges, only: [:new, :create]
  get 'charges/address'
  get 'charges/shipping'
  post 'charges/update_order'
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def address
    @user = current_user
    @products = current_order.order_items.all
  end


  def update_order
    @order = current_order
    if @order.update_order_from_shipping_page(params[:order][:shipping])
      redirect_to new_charge_path and return
    else
      redirect_back(fallback_location: root_path)
      flash[:notice] = "Something is amuck."
    end
  end

  def shipping
    @user = current_user
    @products = current_order.order_items.all
    @order = current_order

    @envelope_weight = 0
    @not_envelope = 0
    @products.each do |thing|
      if thing.product.envelope
        @envelope_weight += thing.product.weight
      else
        @not_envelope += 1
      end
    end

    if @not_envelope == 0
      # shipping for envelope
    else
      packages =  []
      @products.each do |thing|
        unless thing.product.envelope
          if thing.id == 1
            packages << ActiveShipping::Package.new( (thing.product.weight + @envelope_weight ) * 16,
            [thing.product.box_length, thing.product.box_width, thing.product.box_depth],
            units: :imperial)
          else
            packages << ActiveShipping::Package.new( thing.product.weight * 16,
            [thing.product.box_length, thing.product.box_width, thing.product.box_depth],
            units: :imperial)
          end # envelope weight if else
        end #unless
      end ## each do
    end # not envelope if/else

    origin = ActiveShipping::Location.new( country: 'US', state: 'CO', city: 'Sedalia', zip: '80135')

    if @user.country == 'US'
      destination = ActiveShipping::Location.new( country: @user.country, state: @user.state, city: @user.city, zip: @user.zip)
    else
      destination = ActiveShipping::Location.new( country: @user.country, province: @user.state, city: @user.city, postal_code: @user.zip)
    end # if/else for country

    ups = ActiveShipping::UPS.new(login: 'lizbayardelle', password: 'UPSpassw0rd', key: '3D287D7B39D0D398')
    ups_response = ups.find_rates(origin, destination, packages)
    @ups_rates = ups_response.rates.sort_by(&:price).collect {|rate| [rate.service_name, rate.price]}

    usps = ActiveShipping::USPS.new(login: '380LINCH6422')
    usps_response = usps.find_rates(origin, destination, packages)
    @usps_rates = usps_response.rates.sort_by(&:price).collect {|rate| [rate.service_name, rate.price]}
  end

  def new
  end ## charges#new

  def create
    # Amount in cents
    @amount = current_order.total * 100
    @user = current_user
    @order = current_order

    if @user.stripe_customer_id
      customer = @user.stripe_customer_id
    else
      customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
      )
      @user.update_attributes(stripe_customer_id: customer.id)
    end
    @order.update_attributes(order_status_id: 2)
    @order.update_attributes(date_placed: DateTime.now)
    OrderMailer.order_placed(@order.user, @order).deliver_now
    session[:order_id] = nil


    charge = Stripe::Charge.create(
      :customer    => @user.stripe_customer_id,
      :amount      => @amount.to_i,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  private

  def order_params
    params.permit(:subtotal, :tax, :shipping, :total, :order_status_id, :user_id, :date_placed, :shipping_choice)
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/_shipping.html.erb
<div class="row text-center">
  <h2 style="font-size: 35px">Billing Information</h2>

  <%= form_tag charges_path do %>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
      <label class="amount text-right">
        <h4><strong>Subtotal: </strong>$<%= number_with_precision( current_order.subtotal, precision: 2 ) %></h4>
        <h4><strong>Tax: </strong>$<%= number_with_precision( current_order.tax, precision: 2 ) %></h4>
        <h4><strong>Shipping: </strong>$<%= number_with_precision( (current_order.total - current_order.subtotal - current_order.tax) / 100 , precision: 2 ) %></h4>
        <h4 style="color: red"><strong>Total: </strong>$<%= number_with_precision( current_order.total, precision: 2 ) %></h4>
      </label>
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="Aloop Order"
            data-amount=<%= current_order.total * 100 %>
            data-locale="auto"></script>
  <% end %>
</div> <!-- stripe checkout row -->

app/views/charges/address.html.erb
<h2 class="text-center">Checkout</h2>

<div class="product-row black-border-row row" style="margin-bottom: 60px">
  <div class="container">

    <div class="row text-center">
      <div class="col-xs-3">
        <h2>1</h2>
        <p>Shipping<br class="visible-xs" /> Address</p>
      </div> <!-- col -->
      <div class="col-xs-3 inactive-step">
        <h2>2</h2>
        <p>Shipping<br class="visible-xs" /> Options</p>
      </div> <!-- col -->
      <div class="col-xs-3 inactive-step">
        <h2>3</h2>
        <p>Billing<br class="visible-xs" /> Information</p>
      </div> <!-- col -->
      <div class="col-xs-3 inactive-step">
        <h2>4</h2>
        <p>Order<br class="visible-xs" /> Confirmation</p>
      </div> <!-- col -->
    </div>

    <div class="row">
      <hr class="col-xs-6 col-xs-push-3" />
    </div>

    <div class="row text-center">
      <h2 style="font-size: 35px">Shipping Address</h2>
      <%= simple_form_for(@user, url: user_path(@user), html: { method: :put }) do |f| %>
        <div class="form-inputs text-left">
          <div class="form-group col-sm-6">
            <%= f.label :street_address_1 %>
            <%= f.text_field :street_address_1, class: "form-control" %>
          </div>
          <div class="form-group col-sm-6">
            <%= f.label :street_address_2 %>
            <%= f.text_field :street_address_2, class: "form-control" %>
          </div>
          <div class="form-group col-sm-6">
            <%= f.label :city %>
            <%= f.text_field :city, class: "form-control" %>
          </div><div class="form-group col-sm-3 col-xs-6">
            <%= f.label :state %>
            <%= f.text_field :state, class: "form-control" %>
          </div><div class="form-group col-sm-3 col-xs-6">
            <%= f.label :zip %>
            <%= f.text_field :zip, class: "form-control" %>
          </div><div class="form-group col-sm-6">
            <%= f.label :provence %>
            <%= f.text_field :provence, class: "form-control" %>
          </div><div class="form-group col-sm-6">
            <%= f.label :country %>
            <%= f.text_field :country, class: "form-control" %>
          </div><div class="form-group">
            <%= f.hidden_field :has_shipping, value: true %>
          </div>
        </div> <!-- form inputs -->
          <%= f.button :submit, "Calculate Shipping" %>
      <% end %>
    </div> <!-- shipping row -->
  </div> <!-- page container -->
</div> <!-- product row -->

<script>
  $(document).ready(function(){
    $(".footer").removeClass("top-shadow-inset");
  });
</script>

app/views/charges/create.html.erb
<h2 class="text-center">Checkout</h2>

<div class="product-row black-border-row row" style="margin-bottom: 60px">
  <div class="container text-center">
    <div class="row text-center">
      <div class="col-xs-3 inactive-step">
        <h2>1</h2>
        <p>Shipping<br class="visible-xs" /> Address</p>
      </div> <!-- col -->
      <div class="col-xs-3 inactive-step">
        <h2>2</h2>
        <p>Shipping<br class="visible-xs" /> Options</p>
      </div> <!-- col -->
      <div class="col-xs-3 inactive-step">
        <h2>3</h2>
        <p>Billing<br class="visible-xs" /> Information</p>
      </div> <!-- col -->
      <div class="col-xs-3">
        <h2>4</h2>
        <p>Order<br class="visible-xs" /> Confirmation</p>
      </div> <!-- col -->
    </div>

    <div class="row">
      <hr class="col-xs-6 col-xs-push-3" />
    </div>

    <h2>Order Confirmation</h2>
    <h3>Your order has been placed!</h3>
    <p>To see this and all previous orders, go to your <%= link_to "dashboard", user_path(current_user) %>.</p>
  </div> <!-- page container -->
</div> <!-- product row -->

<script>
  $(document).ready(function(){
    $(".footer").removeClass("top-shadow-inset");
  });
</script>

app/views/charges/new.html.erb
<h2 class="text-center">Checkout</h2>

<div class="product-row black-border-row row" style="margin-bottom: 60px">
  <div class="container">
    <div class="row text-center">
      <%= link_to charges_shipping_path do %><div class="col-xs-3 inactive-step">
        <h2>1</h2>
        <p>Shipping<br class="visible-xs" /> Address</p>
      </div> <!-- col --><% end %>
      <%= link_to charges_address_path do %><div class="col-xs-3 inactive-step">
        <h2>2</h2>
        <p>Shipping<br class="visible-xs" /> Options</p>
      </div> <!-- col --><% end %>
      <div class="col-xs-3">
        <h2>3</h2>
        <p>Billing<br class="visible-xs" /> Information</p>
      </div> <!-- col -->
      <div class="col-xs-3 inactive-step">
        <h2>4</h2>
        <p>Order<br class="visible-xs" /> Confirmation</p>
      </div> <!-- col -->
    </div>

    <div class="row">
      <hr class="col-xs-6 col-xs-push-3" />
    </div>

  <div class="row">
    <%= render "shipping" %>
  </div> <!-- page container -->
</div> <!-- product row -->

<script>
  $(document).ready(function(){
    $(".footer").removeClass("top-shadow-inset");
  });
</script>

app/views/charges/shipping.html.erb
<h2 class="text-center">Checkout</h2>

<div class="product-row black-border-row row" style="margin-bottom: 60px">
  <div class="container">

    <div class="row text-center">
      <%= link_to charges_shipping_path do %><div class="col-xs-3 inactive-step">
        <h2>1</h2>
        <p>Shipping<br class="visible-xs" /> Address</p>
      </div> <!-- col --><% end %>
      <div class="col-xs-3">
        <h2>2</h2>
        <p>Shipping<br class="visible-xs" /> Options</p>
      </div> <!-- col -->
      <div class="col-xs-3 inactive-step">
        <h2>3</h2>
        <p>Billing<br class="visible-xs" /> Information</p>
      </div> <!-- col -->
      <div class="col-xs-3 inactive-step">
        <h2>4</h2>
        <p>Order<br class="visible-xs" /> Confirmation</p>
      </div> <!-- col -->
    </div>

    <div class="row">
      <hr class="col-xs-6 col-xs-push-3" />
    </div>

    <div class="row text-center">
      <h2 style="font-size: 35px">Shipping Options</h2>
        <% shipping_choices = [] %>
        <% @usps_rates.each do |rate| %>
          <% choice = [] %>
          <% choice << rate[1].to_s + "-" + rate[0].to_s %> <!-- value -->
          <% choice << number_to_currency(rate[1]/100).to_s + " - " + rate[0].to_s %>
          <% shipping_choices << choice %>
        <% end %>
      <%= simple_form_for @order, url: charges_update_order_path(:shipping), method: :post do |f| %>
        <div class="row">
          <div class="form-inputs text-left">
            <div class="form-group col-sm-6">
              <%= f.collection_radio_buttons :shipping, shipping_choices, :first, :last, item_wrapper_class: :block_radio_button_collection %>
            </div>
          </div> <!-- form inputs -->
        </div> <!-- choices row -->
        <div class="row">
        <%= f.button :submit, "Calculate Shipping" %>
      </div>
      <% end %>
    </div> <!-- shipping row -->


  </div> <!-- page container -->
</div> <!-- product row -->

<script>
$(document).ready(function(){
  $(".footer").removeClass("top-shadow-inset");
});
</script>